export enum CategorySuggestionTypes {
  'room',
  'location',
  'floor',
  'usage',
  'buildingFloor',
}

export enum Filters {
  floor = 'floor',
  room = 'room',
  bathroom = 'bathroom',
  masterBedroom = 'masterBedroom',
  window = 'window',
  windowUnit = 'windowUnit',
  door = 'door',
  balconyUnit = 'balconyUnit',
  buildingFloor = 'buildingFloor',
  garage = 'garage',
  paymentMethod = 'paymentMethod',
  barter = 'barter',
  landLicense = 'landLicense',
  landUsage = 'landUsage',
  objectType = 'objectType',
  serviceType = 'serviceType',
  phone = 'phone',
  price = 'price',
  unitPrice = 'unitPrice',
  area = 'area',
  operation = 'operation',
  licenseOperation = 'licenseOperation',
  validDate = 'validDate',
  district = 'district',
  committee = 'committee',
  location = 'location',
  town = 'town',
  howFloor = 'howFloor',
  officeName = 'officeName',
  buildingName = 'buildingName',
  tradeService = 'tradeService',
}

export function getFilter(filter: Filters): any {
  switch (filter) {
    case Filters.buildingFloor:
      return {
        id: Filters.buildingFloor,
        name: 'Барилгын давхар',
        values: [
          'B1',
          'B2',
          '1',
          '2',
          '3',
          '4',
          '5',
          '6',
          '7',
          '8',
          '9',
          '10',
          '11',
          '12',
          '13',
          '14',
          '15',
          '16',
          '17',
          '18',
          '19',
          '20',
          '21',
          '22',
          '23',
          '24',
          '25',
          '26',
          '27',
          '28',
          '29',
          '30',
        ],
        value: '',
        type: 'dropdown',
      };
    case Filters.room:
      return {
        id: Filters.room,
        name: 'Өрөөний тоо',
        values: ['1', '2', '3', '4', '5', '5+'],
        value: '',
        type: 'dropdown',
      };
    case Filters.bathroom:
      return {
        id: Filters.bathroom,
        name: 'Угаалгын өрөөний тоо',
        values: ['Байхгүй', '1', '2', '2+'],
        value: '',
        type: 'dropdown',
      };
    case Filters.masterBedroom:
      return {
        id: Filters.masterBedroom,
        name: 'Мастер унтлагын өрөөний тоо',
        values: ['Байхгүй', '1', '2', '2+'],
        value: '',
        type: 'dropdown',
      };
    case Filters.window:
      return {
        id: Filters.window,
        name: 'Цонх',
        values: ['Вакум', 'Модон', 'Төмөр вакум', 'Модон вакум'],
        value: '',
        type: 'dropdown',
      };
    case Filters.windowUnit:
      return {
        id: Filters.windowUnit,
        name: 'Цонхны тоо',
        values: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '10+'],
        value: '',
        type: 'dropdown',
      };
    case Filters.door:
      return {
        id: Filters.door,
        name: 'Хаалга',
        values: ['Бүргэд', 'Төмөр', 'Мод'],
        value: '',
        type: 'dropdown',
      };
    case Filters.balconyUnit:
      return {
        id: Filters.balconyUnit,
        name: 'Тагтны тоо',
        values: ["Байхгүй", '1', '2', '3', '4', '5', '5+'],
        value: '',
        type: 'dropdown',
      };

    case Filters.floor:
      return {
        id: Filters.floor,
        name: 'Шал',
        values: [
          'Паркет',
          'Ламинат',
          'Плита',
          'Мод',
          'Чулуу',
          'Бетон',
          'Цемент',
        ],
        value: '',
        type: 'dropdown',
      };
    case Filters.garage:
      return {
        id: Filters.garage,
        name: 'Гараж',
        values: ['Байхгүй', 'Байгаа'],
        value: '',
        type: 'dropdown',
      };

    case Filters.paymentMethod:
      return {
        id: Filters.paymentMethod,
        name: 'Төлбөрийн нөхцөл',
        values: ['Банкны лизингтэй', 'Хувь лизингтэй', 'Бэлэн'],
        value: '',
        type: 'dropdown',
      };
    case Filters.barter:
      return {
        id: Filters.barter,
        name: 'Бартер',
        values: ['Байгаа', 'Байхгүй'],
        value: '',
        type: 'dropdown',
      };
    case Filters.district:
      return {
        id: Filters.district,
        name: 'Дүүрэг',
        values: [],
        value: '',
        type: 'dropdown',
      };
    case Filters.committee:
      return {
        id: Filters.committee,
        name: 'Хороо',
        values: [],
        value: '',
        type: 'text',
      };
    case Filters.location:
      return {
        id: Filters.location,
        name: 'Байршил',
        values: [],
        value: '',
        type: 'dropdown',
      };
    case Filters.town:
      return {
        id: Filters.town,
        name: 'Хотхон',
        values: [
          'Академи-1',
          'Академи-2',
          'Скай Смарт Апартмент',
          'Цагаан орд',
          'Дэлгэрнаран',
          'Хөрш заан',
          'Цэлмэг',
          'Шинэ дүр төрх',
          'Дөл хотхон',
          'Зайсан Апартмент Z хотхон',
          'Хавай',
          'UB town',
          'Зайсан Апартмент 2',
          'Ивээл',
          'Бумба гранд',
          'Визард',
          'Шинэ мөрөөдөл',
          'Миний гэр',
          'Ривэр сайд',
          'Туул ван',
          'Цэнгэг 3',
          'Твин Парк',
          'Скай Тауэр',
          'Оргил',
          'Оргил Стар апартмент',
          'SS гарден',
          'Гэгээнтэн',
          'Парк гарден',
          'Андууд',
          'Алтай хаус',
          'Агниста',
          'Ривэр хилс',
          'Хүннү 2222',
          'Эрдэнийн төгөл',
          'Дондогдулам',
          'Хүннү Плас',
          'Japan Town',
          'Рояал гарден',
          'Токио таун',
          'Гэрлүг виста',
          'Хурд',
          'Цэнгэлдэх',
          'KH апартмент',
          'Романа резидэнс',
          'Глобал таун',
          'Жаргалан',
          'Нархан',
          'Бүти таун',
          'Хансвилл',
          'Акояа резидэнс',
          'Кинг Тауэр',
          'Ривэр гарден',
          'Маршал таун',
          'Туул гарден',
          'Бусад',
        ],
        value: '',
        type: 'dropdown',
      };
    case Filters.tradeService:
      return {
        id: Filters.tradeService,
        name: 'Худалдаа үйлчилгээний газрууд',
        values: [
          'Жем палас',
          'Жем молл',
          'Максмолл',
          'Минж плаза',
          'Элбэг их дэлгүүр',
          'Гурванбилэг их дэлгүүр',
          'Алтантөгрөг худалдааны төв',
          'Ачлал их дэлгүүр',
          'Түмэн плаза ',
          'Номин плаза',
          'Авто плаза',
          'Москва их дэлгүүр',
          '1000-н нэрийн бараа',
          'Билэг их дэлгүүр',
          'Kорал центр',
          'Баянгол их дэлгүүр',
          'UK тауэр',
          'Биг барилгын материалын төв',
          'Гермес центр',
          'Нью Сандэй Плаза',
          'Хархорин зах',
          'Ханбүргэдэй',
          'Соло молл',
          'Соманг плаза',
          'Сандэй плаза',
          'Энканто молл',
          'Дүнжингарав худалдааны төв',
          'Баялаг-Ундраа зах',
          'Нарантуул зах',
          'Түмэн молл',
          'Баянзүрх их дэлгүүр',
          'Сэнтралл молл',
          'Натур худалдааны төв',
          'Наран супермаркет',
          'Cinema Next',
          'Саппоро худалдааны төв',
          'Гурвалжин барилгын материалын төв',
          'Драгон молл',
          'Улаанбаатар их дэлгүүр',
          'Шангри-Ла молл',
          'Сэнтрал тауэр',
          'Метромолл',
          'Бльюмон центр',
          'Сөүл плаза',
          'Наран молл',
          'Наран плаза',
          'Төгөлдөр төв',
          'Галлерей Улаанбаатар',
          'Авто плаза',
          'UB март төв',
          'Выставка',
          'Хүннү молл',
          'Наадам центр',
          'Мишээл экспо',
          'Зайсан Стар молл',
          'Голден Будда Шоппинг молл',
          'Зайсан Хилл',
          'Зайсан Скуэр центр',
          'Улсын их дэлгүүр',
          'Пийс молл',
          'Мөнгөн завьяа худалдааны төв',
          'Алтай центр',
          'Цэцэг төв',
          'Монтел утасны дэлгүүр',
          'Бөмбөгөр-1 худалдааны төв',
          'Бөмбөгөр-2 худалдааны төв',
          'Алтжин бөмбөгөр худалдааны төв',
          'Тэди худалдааны төв',
          'МН тауэр',

          'Бусад',
        ],
        value: '',
        type: 'dropdown',
      };
    case Filters.howFloor:
      return {
        id: Filters.howFloor,
        name: 'Хэдэн давхар',
        values: [],
        value: '',
        maxValue: '',
        type: 'dropdown',
        parentId: Filters.buildingFloor,
      };
    case Filters.serviceType:
      return {
        id: Filters.serviceType,
        name: 'Үйлчилгээний төрөл',
        values: [
          'Зоогийн газар',
          'Лангуу, павилон, ТҮЦ',
          'Ресторан, бар, караоке',
          'Супермаркет',
          'Үйлчилгээний талбай',
          'Үсчин гоо, сайхан',
          'Хүнсний дэлгүүр',
          'Бусад',
        ],
        value: '',
        type: 'dropdown',
      };
    case Filters.objectType:
      return {
        id: Filters.objectType,
        name: 'Объектын төрөл',
        values: [
          'Агуулах',
          'Авто засварын газар',
          'Авто угаалгын газар',
          'Үйлдвэр',
          'Зоорь',
          'Бие даасан объект',
          'Зочид буудал',
          'Бусад',
        ],
        value: '',
        type: 'dropdown',
      };
    case Filters.landLicense:
      return {
        id: Filters.landLicense,
        name: 'Газар эзэмшлийн хэлбэр',
        values: ['Өмчлөх', 'Эзэмших', 'Ашиглах'],
        value: '',
        type: 'dropdown',
      };
    case Filters.phone:
      return {
        id: Filters.phone,
        name: 'Утас',
        values: [],
        value: '',
        type: 'text',
      };
    case Filters.area:
      return {
        id: Filters.area,
        name: 'Талбай',
        values: [],
        value: '',
        maxValue: '',
        mark: 'area',
        type: 'text',
      };
    case Filters.officeName:
      return {
        id: Filters.officeName,
        name: 'Оффисын нэр',
        values: [
          'MPM бюлдинг',
          'Рокмон бюлдинг',
          'Гранд плаза',
          'МҮСТО',
          'Эрхи төв',
          'Жем палас',
          'Соманг Плаза',
          'Юу Би тауэр',
          'Мандала тауэр',
          'Сакура тауэр',
          'Ворлд вайн центр',
          'Эрхэт оффис',
          'Блю Скай тауэр',
          'Шангри-ла Улаанбаатар',
          'Мерү тауэр',
          'Даун Таун оффис',
          'Аюуд тауэр',
          'Гранд оффис центр',
          'Юу Би Эйч центр',
          'Мидтаун оффис',
          'Шүрэн бюлдинг',
          'Скай плаза',
          'Далай тауэр',
          'Юнион бюлдинг',
          'Ай Си Си тауэр',
          'Соёмбо тауэр',
          'Гэрэгэ тауэр',
          'Сэнтрум оффис',
          'Про ван оффис',
          'Туушин',
          'Твин тауэр',
          'Лагшин төв',
          'Тайм Классик тауэр',
          'Бльюмон центр',
          'Сэнтрал тауэр',
          'Сити тауэр',
          'Cити центр',
          'Эрдэм тауэр',
          'Хоймор оффис',
          'Компьютер молл',
          'Мөнх тауэр',
          'Ривер тауэр',
          'Кэй Би тауэр',
          'Галакси тауэр',
          'Regis place',
          'Хан-Уул тауэр',
          'Бодь тауэр',
          'Экспресс тауэр',
          'Пийс тауэр',
          'Пэрл тауэр',
          'Капитал центр',
          'Макс тауэр',
          'МН тауэр',
          'М плаза',
          'Корпорейт тауэр',
          'Бусад'
        ],
        value: '',
        maxValue: '',
        type: 'dropdown',
      };
    case Filters.buildingName:
      return {
        id: Filters.buildingName,
        name: 'Барилгын нэр',
        values: [
          'Наадам центр',
          'Хүннү молл',
          "Мишээл экспо",
          "Зайсан Стар молл",
          "Голден Будда Шоппинг молл",
          "Зайсан Хилл",
          "Зайсан Скуэр центр",
          "Бусад"
        ],
        value: '',
        maxValue: '',
        type: 'dropdown',
      };
    case Filters.price:
      return {
        id: Filters.price,
        name: 'Үнэ',
        values: [],
        value: '',
        maxValue: '',
        type: 'text',
      };
    case Filters.unitPrice:
      return {
        id: Filters.unitPrice,
        name: 'Нэгж талбайн үнэ',
        values: [],
        value: '',
        mark: 'price',
        type: 'disabled',
        condition: [Filters.price, Filters.area],
      };
    case Filters.operation:
      return {
        id: Filters.operation,
        name: 'Ашиглалтад орсон он',
        values: [],
        value: '',
        maxValue: '',
        mark: 'year',
        type: 'number',
      };
    case Filters.licenseOperation:
      return {
        id: Filters.licenseOperation,
        name: 'Гэрчилгээ олгосон он',
        values: [],
        value: '',
        maxValue: '',
        mark: 'year',
        type: 'number',
      };
    case Filters.validDate:
      return {
        id: Filters.validDate,
        name: 'Хүчинтэй хугацаа',
        values: [],
        value: '',
        maxValue: '',
        type: 'date',
      };
    case Filters.landUsage:
      return {
        id: Filters.landUsage,
        name: 'Газрын зориулалт',
        values: [
          '4 ба түүнээс доош давхар нийтийн орон сууц',
          '5-8 давхар нийтийн орон сууц',
          '9 ба түүнээс дээш давхар нийтийн орон сууц',
          'Авто замын барилга, байгууламж',
          'Авто тээврийн хэрэгслийн зогсоолын талбай',
          'Автомашины гараж',
          'Автомашины засвар, үйлчилгээний газар',
          'Автотээврийн үйлчилгээний зориулалтын барилга, байгууламж',
          'Аж ахуйн',
          'Амины орон сууц',
          'Амралтын газар',
          'Гэр бүлийн хэрэгцээний зуслангийн газар',
          'Гэр, орон сууцны хашааны газар',
          'Жимс, жимсгэний усалгаагүй тариалан',
          'Зочид буудлын цогцолбор',
          'Морин уралдааны бариа, автоспортын уралдааны газар',
          'Нийтийн эзэмшлийн бусад газар',
          'Оршуулгын газар',
          'Өвөлжөө, хаваржаа',
          'Рашаан, сувиллын газар',
          'Техникийн ургамлын усалгаагүй тариалан',
          'Тоглоомын талбай',
          'Ус түгээх цэг',
          'Усан оргилуур',
          'Уул уурхайн үйлдвэрлэлийн барилга, байгууламж',
          'Үйлдвэрийн албан контор',
          'Үйлдвэрлэлийн барилга, байгууламж, бусад газар',
          'Худалдаа, нийтийн үйлчилгээний газар, төв, цогцолбор',
          'Хүүхдийн зуслан',
          'Цэнгэлдэх хүрээлэн, наадмын талбай',
          'Шатах, тослох материал түгээгүүрийн газар, агуулах, ШТС',
          'Эмийн болон гоёлын ургамлын усалгаагүй тариалан',
          'Бусад',
        ],
        value: '',
        type: 'dropdown',
      };
  }
}
